### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by hosseind88** [Erfaniaa/crypto-trading-strategy-backtester#1]
Hi, I get this error when I run ```python3 main.py```
```
ModuleNotFoundError: No module named 'pandas'
```

**Comment by Erfaniaa** [comment]
I'll put pandas in the `requirements.txt` and you should install the Pandas package before running `main.py`.

**Comment by Erfaniaa** [comment]
Pull the repository again and run it again. The problem is solved.
