### ISSUE TITLE
Error downloading candles data 

### ISSUE THREAD

**Issue by sbhadade** [Erfaniaa/crypto-trading-strategy-backtester#3]
Getting this error after running main.py in colab 

`ERROR in download_or_load_candles m1
Downloading m1 candles...
0 / 264
ERROR in download_or_load_candles m1
Downloading m1 candles...
0 / 264`

**Comment by sbhadade** [comment]
@Erfaniaa please guide me on this

**Comment by Erfaniaa** [comment]
Dear @sbhadade,

I talk to you personally, I hope your issue is solved now.

**Comment by sbhadade** [comment]
Thanks a lot for your reply..
I send some mote messages.. Looking for valuable insights.
Thanks & Regards

**Comment by Erfaniaa** [comment]
You are welcome.

**Comment by sbhadade** [comment]
Awesome, thanks!

**Comment by rfabes21** [comment]
> Dear @sbhadade,
> 
> I talk to you personally, I hope your issue is solved now.

@Erfaniaa I am also getting this error after pulling the repo and running `python3 main.py` is there a published fix for this?

**Comment by aimzieslol** [comment]
Can you post the solution here?
